# Generated by Django 4.2.1 on 2023-05-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
