# Generated by Django 4.2.1 on 2023-05-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_rename_employeeexperience_employee_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_experience',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
